In [7]:
import numpy as np

In [8]:
score = np.array([[80, 89, 86, 67, 79],
[78, 97, 89, 67, 81],
[90, 94, 78, 67, 74],
[91, 91, 90, 67, 69],
[76, 87, 75, 67, 86],
[70, 79, 84, 67, 84],
[94, 92, 93, 67, 64],
[86, 85, 83, 67, 80]])

In [9]:
type(score)

numpy.ndarray

### ndarray与Python原生list效率对比

In [10]:
import random
import time

In [11]:
# 生成一个大数组
python_list=[]

for i in range(100000000):
    python_list.append(random.random())


In [12]:
ndarray_list=np.array(python_list)
ndarray_list

array([0.72860737, 0.77010569, 0.4473134 , ..., 0.7597862 , 0.32766801,
       0.81101457])

In [13]:
len(ndarray_list)

100000000

# 原生pythonlist求和

In [14]:
t1=time.time()
a=sum(python_list)
t2=time.time()
d1=t2-t1

t3=time.time()
b=np.sum(ndarray_list)
t4=time.time()
d2=t4-t3

In [15]:
d1

0.9355697631835938

In [16]:
d2

0.2625770568847656

# ndarray的属性

In [17]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [18]:
score.shape # (8,5)

(8, 5)

In [19]:
score.ndim

2

In [20]:
score.size

40

In [21]:
score.dtype

dtype('int32')

In [22]:
score.itemsize

4

# ndarray的形状

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3,4])
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b

array([1, 2, 3, 4])

In [26]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [27]:
a.ndim

2

In [32]:
a.shape

(2, 3)

In [33]:
b.shape

(4,)

In [28]:
b.ndim

1

In [29]:
c.ndim

3

In [30]:
c.shape

(2, 2, 3)

# ndarray的类型

In [31]:
score.dtype

dtype('int32')

# 生成0和1

In [36]:
np.zeros((3,4),dtype="float32")

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [40]:
np.ones(shape=[2,3],dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [41]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [42]:
data1=np.array(score)

In [43]:
data1

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [44]:
data2=np.asarray(score)

In [45]:
data2

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [46]:
data3=np.copy(score)

In [47]:
data3

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [50]:
score[3,1]=1000

# 生成固定范围的数组

In [52]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [56]:
np.arange(0,25,5)

array([ 0,  5, 10, 15, 20])