In [1]:
import numpy as np

In [2]:
import random

# 股票涨幅统计运算

In [3]:
temp=np.array([[ 1.1       , -0.45576704,  0.29667843,  0.16606916],
       [ 0.36775845,  0.24078108,  0.122042  ,  1.1       ],
       [-1.48252741, -0.69347186,  1.1       , -0.30606473],
       [ 0.39438905, -1.31770556,  1.1       , -1.52812773]])

In [4]:
temp

array([[ 1.1       , -0.45576704,  0.29667843,  0.16606916],
       [ 0.36775845,  0.24078108,  0.122042  ,  1.1       ],
       [-1.48252741, -0.69347186,  1.1       , -0.30606473],
       [ 0.39438905, -1.31770556,  1.1       , -1.52812773]])

In [8]:
temp.max(axis=0)

array([1.1       , 0.24078108, 1.1       , 1.1       ])

In [9]:
np.max(temp,axis=1)

array([1.1, 1.1, 1.1, 1.1])

In [10]:
np.max(temp,axis=-1)

array([1.1, 1.1, 1.1, 1.1])