In [1]:
import numpy as np

In [2]:
import random

In [3]:
arr = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])

In [4]:
arr / 10

array([[0.1, 0.2, 0.3, 0.2, 0.1, 0.4],
       [0.5, 0.6, 0.1, 0.2, 0.3, 0.1]])

In [5]:
arr+10

array([[11, 12, 13, 12, 11, 14],
       [15, 16, 11, 12, 13, 11]])

In [7]:
arr*10

array([[10, 20, 30, 20, 10, 40],
       [50, 60, 10, 20, 30, 10]])

In [11]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]]) # (2,6)
arr2 = np.array([[1], [3]])# (2,1)