In [3]:
import numpy as np

In [4]:
import random

In [5]:
stock_change=np.random.normal(loc=0,scale=1,size=(8,10))

In [6]:
stock_change

array([[-1.43532373,  1.05745622, -2.47763275,  0.34180652,  1.25858578,
        -0.36000485, -1.43859254,  0.69914217,  0.83709289,  1.20044132],
       [-0.13248637, -0.11908597, -0.31820022, -1.17963948,  0.38775023,
        -0.02182454, -2.03112787, -1.48611408, -0.98973168,  0.80637259],
       [-0.95301668, -1.20504429,  0.59120027, -0.83639894, -1.08226046,
         0.36145411,  0.22716527,  0.33999593,  0.86457243, -1.09826711],
       [ 1.28513315, -1.05893826,  0.61755462, -0.8209103 , -1.20040637,
         0.78414294, -0.36149875, -0.61333462, -0.73561838, -1.50907589],
       [ 1.51454103,  0.88394968, -0.46871143, -0.74197087,  0.86864628,
        -1.67251533, -0.58806584,  3.25015009, -1.55396937,  0.74122706],
       [-0.8920969 ,  0.12491169,  1.33147606,  1.02320078, -0.73726059,
         1.42757024,  1.44785931, -0.03179479, -0.56168466, -1.3595825 ],
       [ 2.16225131,  0.66481219,  0.11932421,  0.86712469, -1.65859789,
         0.70296048, -0.290134  ,  1.50401322

In [7]:
stock_change>0.5

array([[False,  True, False, False,  True, False, False,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False,  True, False, False, False, False, False,  True,
        False],
       [ True, False,  True, False, False,  True, False, False, False,
        False],
       [ True,  True, False, False,  True, False, False,  True, False,
         True],
       [False, False,  True,  True, False,  True,  True, False, False,
        False],
       [ True,  True, False,  True, False,  True, False,  True,  True,
         True],
       [False, False,  True,  True, False, False,  True,  True, False,
         True]])

In [8]:
stock_change[stock_change>0.5]=1.1

In [9]:
stock_change

array([[-1.43532373,  1.1       , -2.47763275,  0.34180652,  1.1       ,
        -0.36000485, -1.43859254,  1.1       ,  1.1       ,  1.1       ],
       [-0.13248637, -0.11908597, -0.31820022, -1.17963948,  0.38775023,
        -0.02182454, -2.03112787, -1.48611408, -0.98973168,  1.1       ],
       [-0.95301668, -1.20504429,  1.1       , -0.83639894, -1.08226046,
         0.36145411,  0.22716527,  0.33999593,  1.1       , -1.09826711],
       [ 1.1       , -1.05893826,  1.1       , -0.8209103 , -1.20040637,
         1.1       , -0.36149875, -0.61333462, -0.73561838, -1.50907589],
       [ 1.1       ,  1.1       , -0.46871143, -0.74197087,  1.1       ,
        -1.67251533, -0.58806584,  1.1       , -1.55396937,  1.1       ],
       [-0.8920969 ,  0.12491169,  1.1       ,  1.1       , -0.73726059,
         1.1       ,  1.1       , -0.03179479, -0.56168466, -1.3595825 ],
       [ 1.1       ,  1.1       ,  0.11932421,  1.1       , -1.65859789,
         1.1       , -0.290134  ,  1.1       

In [10]:
np.all(stock_change[0:2, 0:5] > 0)

False

In [11]:
np.any(stock_change[:5, :] > 0)

True

# 三目运算符

In [12]:
# 判断前四个股票前四天的涨跌幅 大于0的置为1，否则为0
temp = stock_change[:4, :4]

In [13]:
temp

array([[-1.43532373,  1.1       , -2.47763275,  0.34180652],
       [-0.13248637, -0.11908597, -0.31820022, -1.17963948],
       [-0.95301668, -1.20504429,  1.1       , -0.83639894],
       [ 1.1       , -1.05893826,  1.1       , -0.8209103 ]])

In [14]:
np.where(temp>0,1,0)

array([[0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0]])

In [15]:
temp>0

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False,  True, False],
       [ True, False,  True, False]])

In [16]:
np.where([[False,  True, False,  True],
       [False, False, False, False],
       [False, False,  True, False],
       [ True, False,  True, False]],1,0)

array([[0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0]])

In [17]:
temp

array([[-1.43532373,  1.1       , -2.47763275,  0.34180652],
       [-0.13248637, -0.11908597, -0.31820022, -1.17963948],
       [-0.95301668, -1.20504429,  1.1       , -0.83639894],
       [ 1.1       , -1.05893826,  1.1       , -0.8209103 ]])

In [18]:
# 判断前四个股票前四天的涨跌幅 大于0.5并且小于1的，换为1，否则为0
# 判断前四个股票前四天的涨跌幅 大于0.5或者小于-0.5的，换为1，否则为0
# (temp > 0.5) and (temp < 1)
np.logical_and(temp > 0.5, temp < 1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])